CREATE TABLE `program_activity_draw` (
                                         `id` int(11) NOT NULL AUTO_INCREMENT,
                                         `aid` int(11) NOT NULL DEFAULT '0' COMMENT '频道标志',
                                         `uin` int(11) NOT NULL,
                                         `title` varchar(60) NOT NULL DEFAULT '' COMMENT '抽奖主题',
                                         `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '抽奖类型  1即时抽奖2定时抽奖',
                                         `times` tinyint(2) NOT NULL DEFAULT '1' COMMENT '抽奖次数',
                                         `intro` varchar(150) DEFAULT '' COMMENT '介绍',
                                         `winningInstructions` varchar(150) DEFAULT '' COMMENT '中奖说明',
                                         `limitNumOfWin` int(7) NOT NULL DEFAULT '0' COMMENT '0为不限制',
                                         `condition` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1倒计时 2参与人数',
                                         `countDown` int(10) NOT NULL DEFAULT '0' COMMENT '倒计时',
                                         `joinNum` int(10) DEFAULT '0' COMMENT '参与人数',
                                         `winningRate` float(2,0) NOT NULL DEFAULT '0' COMMENT '中奖率',
  `isShowPrize` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否展示奖品',
  `showRate` int(1) NOT NULL DEFAULT '0' COMMENT '是否显示中奖率',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '抽奖状态',
  `showResult` tinyint(1) NOT NULL DEFAULT '1' COMMENT '中奖名单是否开启 1开启0关闭',
  `showType` tinyint(1) NOT NULL DEFAULT '1' COMMENT '抽奖样式 1九宫格',
  `nowPlay` tinyint(1) NOT NULL DEFAULT '1' COMMENT '当前场次',
  `totalPlay` tinyint(2) NOT NULL DEFAULT '1' COMMENT '总共场次',
  `startTime` int(11) NOT NULL COMMENT '开启时间',
  `endTime` int(11) NOT NULL COMMENT '关闭时间',
  `createTime` int(11) NOT NULL,
  `updateTime` int(11) NOT NULL,
  `sTaskId` int(10) DEFAULT '0',
  `eTaskId` int(10) DEFAULT '0',
  `isDeleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1000690 DEFAULT CHARSET=utf8;

CREATE TABLE `program_activity_draw_bind` (
                                              `id` int(11) NOT NULL AUTO_INCREMENT,
                                              `drawId` int(11) NOT NULL,
                                              `type` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '绑定类型',
                                              `bindId` int(11) NOT NULL,
                                              `uin` int(11) NOT NULL,
                                              PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `program_activity_draw_play` (
                                              `id` int(11) NOT NULL AUTO_INCREMENT,
                                              `drawId` int(11) NOT NULL,
                                              `play` tinyint(2) NOT NULL DEFAULT '1' COMMENT '场次',
                                              `banner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '宣传图',
                                              `url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '外链地址',
                                              `isShowBanner` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否展示banner',
                                              `winningRate` float(2,0) NOT NULL DEFAULT '0' COMMENT '中奖率',
  `isShowPrize` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否展示奖品',
  `showType` int(4) NOT NULL DEFAULT '1' COMMENT '抽奖样式 1九宫格',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `startTime` int(11) NOT NULL,
  `endTime` int(11) NOT NULL,
  `condition` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1倒计时 2参与人数',
  `countDown` int(10) NOT NULL DEFAULT '0' COMMENT '倒计时',
  `joinNum` int(10) DEFAULT '0' COMMENT '参与人数',
  `specialSwitch` tinyint(1) NOT NULL DEFAULT '0' COMMENT '特殊开关 如口令开关',
  `specialContent` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '特殊内容',
  `prizeType` int(3) NOT NULL DEFAULT '1' COMMENT '奖品类型 1实物',
  `exchangeType` int(4) NOT NULL DEFAULT '1' COMMENT '兑换方式',
  `expiredTime` int(11) DEFAULT '0' COMMENT '有效期 0为永久',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=982 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `program_activity_draw_prize` (
                                               `id` int(11) NOT NULL AUTO_INCREMENT,
                                               `drawId` int(11) NOT NULL COMMENT '抽奖Id',
                                               `playId` int(11) NOT NULL DEFAULT '0' COMMENT '场次id',
                                               `prizeAlias` varchar(10) DEFAULT '' COMMENT '奖项别名',
                                               `level` int(4) NOT NULL DEFAULT '1' COMMENT '奖项级别',
                                               `name` varchar(15) NOT NULL COMMENT '奖品名称',
                                               `num` int(4) NOT NULL DEFAULT '0' COMMENT '已抽中的奖品数量',
                                               `sum` int(4) NOT NULL DEFAULT '0' COMMENT '奖品总数',
                                               `type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '奖品类型 1实物',
                                               `typeInfo` varchar(20) DEFAULT '',
                                               `icon` varchar(150) DEFAULT '' COMMENT '奖品图标',
                                               `url` varchar(255) DEFAULT '',
                                               `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除',
                                               `winningRate` int(4) NOT NULL DEFAULT '0' COMMENT '中奖率',
                                               `createTime` int(11) NOT NULL,
                                               `updateTime` int(11) NOT NULL,
                                               PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1624 DEFAULT CHARSET=utf8;

CREATE TABLE `program_activity_draw_result` (
                                                `id` int(11) NOT NULL AUTO_INCREMENT,
                                                `uin` int(11) NOT NULL,
                                                `drawId` int(11) NOT NULL,
                                                `userId` int(11) NOT NULL,
                                                `phone` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT '',
                                                `userNick` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
                                                `userIp` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '',
                                                `address` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '收货地址',
                                                `avatar` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
                                                `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否核销 0未1已',
                                                `drawPlay` tinyint(2) NOT NULL,
                                                `playId` int(11) NOT NULL DEFAULT '0' COMMENT '场次id',
                                                `prizeId` int(11) NOT NULL,
                                                `exchangeType` tinyint(2) NOT NULL DEFAULT '1' COMMENT '兑换方式',
                                                `prizeName` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
                                                `prizeLevel` tinyint(2) NOT NULL,
                                                `prizeIcon` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '奖品图标',
                                                `drawTime` int(11) NOT NULL,
                                                `source` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'live' COMMENT '来源',
                                                `sourceId` int(11) NOT NULL DEFAULT '0',
                                                `code` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '核销码',
                                                `name` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '联系人',
                                                `contactPhone` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '联系电话',
                                                `tempId` char(36) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '临时id',
                                                PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1892 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;