mysql:
  username: "root"
  password: "AOdian#123"
  path: "121.42.227.165:3306"
  db-name: "broadcast_cloud"
  config: "charset=utf8&parseTime=True&loc=Local"
  max-idle-conns: 20
  max-open-conns: 20
  log-mode: false

redis:
  addr: '121.42.227.165:6379'
  password: 'redisAOdian#123'
  db: 0

system:
  env: "public"
  addr: 8002
  db-type: "mysql"
  mode: "debug"

jwt:
  signing-key: "your_key"

Log:
  path: "logs"
  name: "system.log"

email:
  host: ""
  port: 465
  user: ""
  pass: ""
  admin-user: ""

param:
  b-gateway-host: "http://passdev.guangdianyun.tv"
